export const textosMain = {
    es: { 
        inicio: "INICIO", 
        carta: "CARTA", 
        info: "INFORMACIÓN", 
        mapa: "CONTACTO", 
        subtitulo: "PIZZERIA - RESTAURANTE",
        fecha: "Desde 1996",
        sobreNosotrosMasa: "Masa Artesanal Diaria",
        sobreNosotrosTitulo: "NUESTRA HISTORIA",
        sobreNosotrosTexto: "Desde 1996, en LA NOVA DOLCE nos apasiona ofrecer comida de calidad en el corazón de Santa Pola, Alicante. Lo que nos diferencia es el respeto por la tradición: nuestra masa no es congelada; la elaboramos nosotros mismos cada día, permitiendo que repose el tiempo necesario para lograr esa textura perfecta y artesanal. En nuestro rincón acogedor, cada cliente es parte de la familia, ya sea disfrutando en nuestro local o pidiendo para llevar a casa.",
        horario: "Horario",
        comida: "Comida",
        cena: "Cena",
        eventos: "EVENTOS Y CELEBRACIONES",
        eventosSub: "Queremos celebrar contigo, garantizando la seguridad y salud de todos",
        normaTarta: "Si traes tu tarta, recuerda traer el ticket de compra",
        normaBebes: "Comida de bebé permitida (potitos, biberones)",
        normaReservas: "Reservas: Máximo 10 personas para asegurar tu comodidad",
        lunes: "Lunes",
        martes: "Martes",
        cerrado: "Cerrado",
        miercoles: "Miércoles",
        jueves: "Jueves",
        viernes: "Viernes",
        sabado: "Sábado",
        domingo: "Domingo",
        glovoTitulo: "PIDE A DOMICILIO",
        glovoTexto: "¡Estamos en Glovo! Disfruta de nuestras pizzas sin salir de casa.",
        glovoExclusivo: "Servicio exclusivo en Santa Pola.",
        glovoTiempo: "Entrega estimada: 30 - 45 min",
        glovoBoton: "Pedir en Glovo",
        cartaDescripcion: "Pizzas artesanas, pastas tradicionales y postres caseros.",
        cartaCalidad: "Calidad y sabor desde 1996.",
        cartaPregunta: "¿Te vas a quedar con las ganas?",
        verCarta: "Abrir",
        cerrarCarta: "Cerrar",
        contactoDireccion: "Calle Castaños, 34, Santa Pola",
        Pizzas: "PIZZAS",
        Pastas: "PASTAS",
        Ensaladas: "ENSALADAS",
        Entrantes: "ENTRANTES",
        Carnes: "CARNES",
        Postres: "POSTRES",
        Bebidas: "BEBIDAS",
        pequeña: "P",
        grande: "G",
        incrementoDelPrecio: "Cualquier cambio en los ingredientes llevará un incremento en el precio.",
        consultarSalsas: "Le invitamos a descubrir nuestra selección de salsas en el apartado correspondiente."
    },
    en: { 
        inicio: "HOME", 
        carta: "MENU", 
        info: "INFO", 
        mapa: "CONTACT", 
        subtitulo: "PIZZERIA - RESTAURANT",
        fecha: "Since 1996",
        sobreNosotrosMasa: "Daily Artisanal Dough",
        sobreNosotrosTitulo: "OUR STORY",
        sobreNosotrosTexto: "Since 1996, at LA NOVA DOLCE we have been passionate about offering quality food in the heart of Santa Pola, Alicante. What sets us apart is our respect for tradition: our dough is never frozen; we make it ourselves every day, allowing it to rest for the necessary time to achieve that perfect artisanal texture. In our cozy corner, every customer is part of the family, whether enjoying in our restaurant or ordering to take home.",
        horario: "Opening Hours",
        comida: "Lunch",
        cena: "Dinner",
        eventos: "EVENTS & CELEBRATIONS",
        eventosSub: "We want to celebrate with you, ensuring everyone's safety and health",
        normaTarta: "If you bring your own cake, please remember to bring the receipt",
        normaBebes: "Baby food allowed (baby jars, bottles)",
        normaReservas: "Reservations: Maximum 10 people for your comfort",
        lunes: "Monday",
        martes: "Tuesday",
        cerrado: "Closed",
        miercoles: "Wednesday",
        jueves: "Thursday",
        viernes: "Friday",
        sabado: "Saturday",
        domingo: "Sunday",
        glovoTitulo: "ORDER DELIVERY",
        glovoTexto: "We are on Glovo! Enjoy our pizzas without leaving home.",
        glovoExclusivo: "Exclusive service in Santa Pola.",
        glovoTiempo: "Estimated delivery: 30 - 45 min",
        glovoBoton: "Order on Glovo",
        cartaDescripcion: "Artisanal pizzas, traditional pasta, and homemade desserts.",
        cartaCalidad: "Quality and flavor since 1996.",
        cartaPregunta: "Are you going to miss out?",
        verCarta: "Open",
        cerrarCarta: "Close",
        contactoDireccion: "Castaños St, 34, Santa Pola",
        Pizzas: "PIZZAS",
        Pastas: "PASTA",
        Ensaladas: "SALADS",
        Entrantes: "STARTERS",
        Carnes: "MEAT",
        Postres: "DESSERTS",
        Bebidas: "DRINKS",
        pequeña: "S",
        grande: "L",
        incrementoDelPrecio: "Any change in ingredients will lead to a price increase.",
        consultarSalsas: "We invite you to discover our selection of sauces in the corresponding section."
    },
    fr: { 
        inicio: "ACCUEIL", 
        carta: "CARTE", 
        info: "INFOS", 
        mapa: "CONTACT", 
        subtitulo: "PIZZERIA - RESTAURANT",
        fecha: "Depuis 1996",
        sobreNosotrosMasa: "Pâte Artisanale Quotidienne",
        sobreNosotrosTitulo: "NOTRE HISTOIRE",
        sobreNosotrosTexto: "Depuis 1996, chez LA NOVA DOLCE, nous sommes passionnés par l'offre d'une cuisine de qualité au cœur de Santa Pola, Alicante. Ce qui nous distingue, c'est le respect de la tradition : notre pâte n'est pas congelée ; nous la fabriquons nous-mêmes chaque jour, en la laissant reposer le temps nécessaire pour obtenir cette texture artisanale parfaite. Dans notre coin chaleureux, chaque client fait partie de la famille, qu'il déguste sur place ou commande à emporter.",
        horario: "Horaires",
        comida: "Déjeuner",
        cena: "Dîner",
        eventos: "ÉVÉNEMENTS ET CÉLÉBRATIONS",
        eventosSub: "Nous voulons célébrer avec vous, en garantissant la sécurité de tous",
        normaTarta: "Si vous apportez votre gâteau, n'oubliez pas le ticket de caisse",
        normaBebes: "Nourriture pour bébés autorisée (petits pots, biberons)",
        normaReservas: "Réservations : Maximum 10 personnes pour votre confort",
        lunes: "Lundi",
        martes: "Mardi",
        cerrado: "Fermé",
        miercoles: "Mercredi",
        jueves: "Jeudi",
        viernes: "Vendredi",
        sabado: "Samedi",
        domingo: "Dimanche",
        glovoTitulo: "COMMANDER À DOMICILE",
        glovoTexto: "Nous sommes sur Glovo ! Profitez de nos pizzas sans sortir de chez vous.",
        glovoExclusivo: "Service exclusif à Santa Pola.",
        glovoTiempo: "Livraison estimée : 30 - 45 min",
        glovoBoton: "Commander sur Glovo",
        cartaDescripcion: "Pizzas artisanales, pâtes traditionnelles et desserts maison.",
        cartaCalidad: "Qualité et saveur depuis 1996.",
        cartaPregunta: "Allez-vous rester sur votre faim ?",
        verCarta: "Ouvrir",
        cerrarCarta: "Fermer",
        contactoDireccion: "Rue Castaños, 34, Santa Pola",
        Pizzas: "PIZZAS",
        Pastas: "PÂTES",
        Ensaladas: "SALADES",
        Entrantes: "ENTRÉES",
        Carnes: "VIANDES",
        Postres: "DESSERTS",
        Bebidas: "BOISSONS",
        pequeña: "P",
        grande: "G",
        incrementoDelPrecio: "Tout changement d'ingrédients entraînera una augmentation du prix.",
        consultarSalsas: "Nous vous invitons à découvrir notre sélection de sauces dans la section correspondante."
    },
    de: { 
        inicio: "START", 
        carta: "SPEISEKARTE", 
        info: "INFOS", 
        mapa: "KONTAKT", 
        subtitulo: "PIZZERIA - RESTAURANT",
        fecha: "Seit 1996",
        sobreNosotrosMasa: "Täglich handgemachter Teig",
        sobreNosotrosTitulo: "UNSERE GESCHICHTE",
        sobreNosotrosTexto: "Seit 1996 widmen wir uns bei LA NOVA DOLCE mit Leidenschaft der hochwertigen Küche im Herzen von Santa Pola, Alicante. Was uns auszeichnet, ist der Respekt vor der Tradition: Unser Teig wird nicht eingefroren; wir stellen ihn jeden Tag selbst her und lassen ihn so lange ruhen, wie es für die perfekte handwerkliche Textur nötig ist. In unserer gemütlichen Ecke gehört jeder Gast zur Familie, egal ob vor Ort oder zum Mitnehmen.",
        horario: "Öffnungszeiten",
        comida: "Mittagessen",
        cena: "Abendessen",
        eventos: "EVENTS UND FEIERLICHKEITEN",
        eventosSub: "Wir möchten mit Ihnen feiern und dabei die Gesundheit aller garantieren",
        normaTarta: "Wenn Sie Ihren Kuchen mitbringen, denken Sie an den Kaufbeleg",
        normaBebes: "Babynahrung erlaubt (Gläschen, Fläschchen)",
        normaReservas: "Reservierungen: Maximal 10 Personen für Ihren Komfort",
        lunes: "Montag",
        martes: "Dienstag",
        cerrado: "Geschlossen",
        miercoles: "Mittwoch",
        jueves: "Donnerstag",
        viernes: "Freitag",
        sabado: "Samstag",
        domingo: "Sonntag",
        glovoTitulo: "LIEFERSERVICE",
        glovoTexto: "Wir sind bei Glovo! Genießen Sie unsere Pizzas ganz entspannt zu Hause.",
        glovoExclusivo: "Exklusiver Service in Santa Pola.",
        glovoTiempo: "Voraussichtliche Lieferung: 30 - 45 Min.",
        glovoBoton: "Bei Glovo bestellen",
        cartaDescripcion: "Hausgemachte Pizzas, traditionelle Pasta und Desserts.",
        cartaCalidad: "Qualität und Geschmack seit 1996.",
        cartaPregunta: "Wollen Sie sich das entgehen lassen?",
        verCarta: "Öffnen",
        cerrarCarta: "Schließen",
        contactoDireccion: "Castaños Straße, 34, Santa Pola",
        Pizzas: "PIZZAS",
        Pastas: "PASTA",
        Ensaladas: "SALATE",
        Entrantes: "VORSPEISEN",
        Carnes: "FLEISCH",
        Postres: "DESSERTS",
        Bebidas: "GETRÄNKE",
        pequeña: "K",
        grande: "G",
        incrementoDelPrecio: "Jede Änderung der Zutaten führt zu einer Preiserhöhung.",
        consultarSalsas: "Wir laden Sie ein, unsere Saucenauswahl im entsprechenden Abschnitt zu entdecken."
    }
};